force-app/main/default/objects/ApexUnexpectedException__c/ApexUnexpectedException__c.object-meta.xml
<CustomObject>
    <label>Apex Unexpected Exception</label>
    <nameField>
        <displayFormat>E-{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Unexpected Exceptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EventLogParser/force-app/main/default/objects/ApexUnexpectedException__c/fields/ExceptionMessage__c.field-meta.xml
<CustomField>
    <fullName>ExceptionMessage__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Exception Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ApexUnexpectedException__c/fields/ExceptionMessageSummary__c.field-meta.xml
<CustomField>
    <fullName>ExceptionMessageSummary__c</fullName>
    <description>For list views and querying.

Set by Apex Trigger ApexUnexpectedExceptionTrigger.  Strips the prefix with the org name from the Exception Message, and abbreviates it to a max of 255 characters.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Exception Message Summary</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ApexUnexpectedExceptionTriggerHandler.cls
public class ApexUnexpectedExceptionTriggerHandler {
    public void beforeInsert(List<ApexUnexpectedException__c> newList) {
        this.populateExceptionMessageSummary(newList);
    }

    public void afterInsert(List<ApexUnexpectedException__c> newList) {

    }

    public void beforeUpdate(List<ApexUnexpectedException__c> newList, Map<Id, ApexUnexpectedException__c> oldMap) {
        this.populateExceptionMessageSummary(newList);
    }

    public void afterUpdate(List<ApexUnexpectedException__c> newList, Map<Id, ApexUnexpectedException__c> oldMap) {

    }

    public void populateExceptionMessageSummary(List<ApexUnexpectedException__c> newList) {
        String expectedPrefix = '"Developer script exception from ' + UserInfo.getOrganizationName() + ' : ';
        for (ApexUnexpectedException__c exc : newList) {
            String msg = exc.ExceptionMessage__c;
            if (msg != null) {
                if (msg.length() >= expectedPrefix.length() && msg.substring(0, expectedPrefix.length()) == expectedPrefix) {
                    msg = '"... ' + msg.substring(expectedPrefix.length());
                }
                msg = msg.abbreviate(255);
            }
            exc.ExceptionMessageSummary__c = msg;
        }
    }
}